# golangci-lint configuration (v2)
# https://golangci-lint.run/product/config-file/

version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
  disable:
    - errcheck
    - unused
    - staticcheck
