name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Brief description of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        As a [user type], I want [goal] so that [benefit].

        Currently, [describe current limitation or pain point]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        I propose [solution] that would work by [explanation].

        For example:
        - Command: `ason new template --option value`
        - Configuration: `config.toml` setting
        - API: New function or method
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        Alternative 1: [description]
        Alternative 2: [description]

        Why the proposed solution is better: [explanation]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - Not sure

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used
      render: shell
      placeholder: |
        # Example 1: Basic usage
        ason new my-template --new-feature value

        # Example 2: Advanced usage
        ason config set feature.option true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Documentation is updated
        - [ ] Tests are included
        - [ ] Backward compatibility is maintained

  - type: checkboxes
    id: area
    attributes:
      label: Related Areas
      description: Which areas of Ason would this feature affect?
      options:
        - label: CLI commands
        - label: Template processing
        - label: Configuration
        - label: Documentation
        - label: Performance
        - label: Security
        - label: Testing

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with Ason's goals and scope
          required: true
        - label: I would be willing to help implement this feature
        - label: I would be willing to help test this feature